/***************************************************************************
 *
 * Copyright 2015-2021 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __REG_CAPSENSOR_BEST1501_H__
#define __REG_CAPSENSOR_BEST1501_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "plat_types.h"

struct CAPSENSOR_T {
    __IO uint32_t REG_00;
    __IO uint32_t REG_04;
    __IO uint32_t REG_08;
    __IO uint32_t REG_0C;
    __IO uint32_t REG_10;
    __IO uint32_t REG_14;
    __IO uint32_t REG_18;
    __IO uint32_t REG_1C;
    __IO uint32_t REG_20;
    __IO uint32_t REG_24;
    __IO uint32_t REG_28;
    __IO uint32_t REG_2C;
    __IO uint32_t REG_30;
    __IO uint32_t REG_34;
    __IO uint32_t REG_38;
    __IO uint32_t REG_3C;
    __IO uint32_t REG_40;
    __IO uint32_t REG_44;
    __IO uint32_t REG_48;
    __IO uint32_t REG_4C;
    __IO uint32_t REG_50;
    __IO uint32_t REG_54;
    __IO uint32_t REG_58;
    __IO uint32_t REG_5C;
    __IO uint32_t REG_60;
    __IO uint32_t REG_64;
    __IO uint32_t REG_68;
    __IO uint32_t REG_6C;
    __IO uint32_t REG_70;
    __IO uint32_t REG_74;
    __IO uint32_t REG_78;
    __IO uint32_t REG_7C;
    __IO uint32_t REG_80;
    __IO uint32_t REG_84;
    __IO uint32_t REG_88;
    __IO uint32_t REG_8C;
    __IO uint32_t REG_90;
    __IO uint32_t REG_94;
    __IO uint32_t REG_98;
    __IO uint32_t REG_9C;
    __IO uint32_t REG_A0;
    __IO uint32_t REG_A4;
    __IO uint32_t REG_A8;
};

// REG_00
#define CAP_SENS_REG_STG_NUM_SHIFT            28
#define CAP_SENS_REG_STG_NUM_MASK             (0x7 << CAP_SENS_REG_STG_NUM_SHIFT)
#define CAP_SENS_REG_STG_NUM(n)               (((n) & CAP_SENS_REG_STG_NUM_MASK) >> CAP_SENS_REG_STG_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT    24
#define CAP_SENS_REG_INTVL1_CONV_NUM_MASK     (0xF << CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_CONV_NUM(n)       (((n) & CAP_SENS_REG_INTVL1_CONV_NUM_MASK) >> CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_SHIFT             16
#define CAP_SENS_REG_INTVL1_MASK              (0xFF << CAP_SENS_REG_INTVL1_SHIFT)
#define CAP_SENS_REG_INTVL1(n)                (((n) & CAP_SENS_REG_INTVL1_MASK) >> CAP_SENS_REG_INTVL1_SHIFT)
#define CAP_SENS_REG_INTVL2_SHIFT             0
#define CAP_SENS_REG_INTVL2_MASK              (0xFFFF << CAP_SENS_REG_INTVL2_SHIFT)
#define CAP_SENS_REG_INTVL2(n)                (((n) & CAP_SENS_REG_INTVL2_MASK) >> CAP_SENS_REG_INTVL2_SHIFT)

// REG_04
#define CAP_SENS_REG_CFG_STG3_SHIFT           24
#define CAP_SENS_REG_CFG_STG3_MASK            (0x1F << CAP_SENS_REG_CFG_STG3_SHIFT)
#define CAP_SENS_REG_CFG_STG3(n)              (((n) & CAP_SENS_REG_CFG_STG3_MASK) >> CAP_SENS_REG_CFG_STG3_SHIFT)
#define CAP_SENS_REG_CFG_STG2_SHIFT           16
#define CAP_SENS_REG_CFG_STG2_MASK            (0x1F << CAP_SENS_REG_CFG_STG2_SHIFT)
#define CAP_SENS_REG_CFG_STG2(n)              (((n) & CAP_SENS_REG_CFG_STG2_MASK) >> CAP_SENS_REG_CFG_STG2_SHIFT)
#define CAP_SENS_REG_CFG_STG1_SHIFT           8
#define CAP_SENS_REG_CFG_STG1_MASK            (0x1F << CAP_SENS_REG_CFG_STG1_SHIFT)
#define CAP_SENS_REG_CFG_STG1(n)              (((n) & CAP_SENS_REG_CFG_STG1_MASK) >> CAP_SENS_REG_CFG_STG1_SHIFT)
#define CAP_SENS_REG_CFG_STG0_SHIFT           0
#define CAP_SENS_REG_CFG_STG0_MASK            (0x1F << CAP_SENS_REG_CFG_STG0_SHIFT)
#define CAP_SENS_REG_CFG_STG0(n)              (((n) & CAP_SENS_REG_CFG_STG0_MASK) >> CAP_SENS_REG_CFG_STG0_SHIFT)

// REG_08
#define CAP_SENS_REG_CFG_STG7_SHIFT           24
#define CAP_SENS_REG_CFG_STG7_MASK            (0x1F << CAP_SENS_REG_CFG_STG7_SHIFT)
#define CAP_SENS_REG_CFG_STG7(n)              (((n) & CAP_SENS_REG_CFG_STG7_MASK) >> CAP_SENS_REG_CFG_STG7_SHIFT)
#define CAP_SENS_REG_CFG_STG6_SHIFT           16
#define CAP_SENS_REG_CFG_STG6_MASK            (0x1F << CAP_SENS_REG_CFG_STG6_SHIFT)
#define CAP_SENS_REG_CFG_STG6(n)              (((n) & CAP_SENS_REG_CFG_STG6_MASK) >> CAP_SENS_REG_CFG_STG6_SHIFT)
#define CAP_SENS_REG_CFG_STG5_SHIFT           8
#define CAP_SENS_REG_CFG_STG5_MASK            (0x1F << CAP_SENS_REG_CFG_STG5_SHIFT)
#define CAP_SENS_REG_CFG_STG5(n)              (((n) & CAP_SENS_REG_CFG_STG5_MASK) >> CAP_SENS_REG_CFG_STG5_SHIFT)
#define CAP_SENS_REG_CFG_STG4_SHIFT           0
#define CAP_SENS_REG_CFG_STG4_MASK            (0x1F << CAP_SENS_REG_CFG_STG4_SHIFT)
#define CAP_SENS_REG_CFG_STG4(n)              (((n) & CAP_SENS_REG_CFG_STG4_MASK) >> CAP_SENS_REG_CFG_STG4_SHIFT)

// REG_0C
#define CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN1_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN1(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN1_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN0_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN0(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN0_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT)

// REG_10
#define CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN3_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN3(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN3_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN2_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN2(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN2_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT)

// REG_14
#define CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN5(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN4_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN4(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN4_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT)

// REG_18
#define CAP_SENS_REG_CAP_OFFSET_CHAN7_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN7_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN7(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN6_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN6(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN6_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT)

// REG_1C
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT        8
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_MASK         (0xFF << CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM(n)           (((n) & CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_MASK) >> CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT          0
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_MASK           (0xFF << CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM(n)             (((n) & CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_MASK) >> CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT)

// REG_20
#define CAP_SENS_REG_CAP_THR_CHAN1_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN1_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN1(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN1_MASK) >> CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN0_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN0_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN0(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN0_MASK) >> CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)

// REG_24
#define CAP_SENS_REG_CAP_THR_CHAN3_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN3_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN3(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN3_MASK) >> CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN2_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN2_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN2(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN2_MASK) >> CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)

// REG_28
#define CAP_SENS_REG_CAP_THR_CHAN5_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN5_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN5(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN5_MASK) >> CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN4_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN4_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN4(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN4_MASK) >> CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)

// REG_2C
#define CAP_SENS_REG_CAP_THR_CHAN7_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN7_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN7(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN7_MASK) >> CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN6_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN6_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN6(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN6_MASK) >> CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)

// REG_30
#define CAP_SENS_REG_CAP_THR_DIFF1_SHIFT        16
#define CAP_SENS_REG_CAP_THR_DIFF1_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF1_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF1(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF1_MASK) >> CAP_SENS_REG_CAP_THR_DIFF1_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF0_SHIFT        0
#define CAP_SENS_REG_CAP_THR_DIFF0_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF0_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF0(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF0_MASK) >> CAP_SENS_REG_CAP_THR_DIFF0_SHIFT)

// REG_34
#define CAP_SENS_REG_CAP_THR_DIFF3_SHIFT        16
#define CAP_SENS_REG_CAP_THR_DIFF3_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF3_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF3(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF3_MASK) >> CAP_SENS_REG_CAP_THR_DIFF3_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF2_SHIFT        0
#define CAP_SENS_REG_CAP_THR_DIFF2_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF2_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF2(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF2_MASK) >> CAP_SENS_REG_CAP_THR_DIFF2_SHIFT)

// REG_38
#define CAP_SENS_REG_NOISE_THR_CHAN1_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN1_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN1(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN1_MASK) >> CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN0_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN0_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN0(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN0_MASK) >> CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)

// REG_3C
#define CAP_SENS_REG_NOISE_THR_CHAN3_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN3_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN3(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN3_MASK) >> CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN2_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN2_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN2(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN2_MASK) >> CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)

// REG_40
#define CAP_SENS_REG_NOISE_THR_CHAN5_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN5_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN5(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN5_MASK) >> CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN4_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN4_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN4(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN4_MASK) >> CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)

// REG_44
#define CAP_SENS_REG_NOISE_THR_CHAN7_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN7_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN7(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN7_MASK) >> CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN6_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN6_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN6(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN6_MASK) >> CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)

// REG_48
#define CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT       24
#define CAP_SENS_REG_CHANN_SEL_DIFF3_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF3(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF3_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT       16
#define CAP_SENS_REG_CHANN_SEL_DIFF2_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF2(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF2_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT       8
#define CAP_SENS_REG_CHANN_SEL_DIFF1_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF1(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF1_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT       0
#define CAP_SENS_REG_CHANN_SEL_DIFF0_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF0(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF0_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT)

// REG_4C
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT       24
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT       16
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT       8
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT       0
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT)

// REG_50
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT    16
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_MASK     (0xFFFF << CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN(n)       (((n) & CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_MASK) >> CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT    0
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_MASK     (0xFFFF << CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX(n)       (((n) & CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_MASK) >> CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT)

// REG_54
#define CAP_SENS_REG_VCORE_PWUP_1            (1 << 28)
#define CAP_SENS_REG_VCORE_PWUP_0            (1 << 27)
#define CAP_SENS_REG_VCORE_PWUP_DR           (1 << 26)
#define CAP_SENS_REG_CDC_CORE_RST            (1 << 25)
#define CAP_SENS_REG_CDC_CORE_RST_DR         (1 << 24)
#define CAP_SENS_REG_CDC_CORE_PWUP           (1 << 21)
#define CAP_SENS_REG_CDC_CORE_PWUP_DR        (1 << 20)
#define CAP_SENS_REG_VREF_PRECHG             (1 << 17)
#define CAP_SENS_REG_VREF_PRECHF_DR          (1 << 16)
#define CAP_SENS_REG_RCOSC_PWUP_1            (1 << 14)
#define CAP_SENS_REG_RCOSC_PWUP_0            (1 << 13)
#define CAP_SENS_REG_RCOSC_PWUP_DR           (1 << 12)
#define CAP_SENS_REG_LDO_PWUP_1              (1 << 10)
#define CAP_SENS_REG_LDO_PWUP_0              (1 << 9)
#define CAP_SENS_REG_LDO_PWUP_DR             (1 << 8)
#define CAP_SENS_REG_VREF_PWUP_1             (1 << 6)
#define CAP_SENS_REG_VREF_PWUP_0             (1 << 5)
#define CAP_SENS_REG_VREF_PWUP_DR            (1 << 4)
#define CAP_SENS_REG_BIAS_PWUP_1             (1 << 2)
#define CAP_SENS_REG_BIAS_PWUP_0             (1 << 1)
#define CAP_SENS_REG_BIAS_PWUP_DR            (1 << 0)

// REG_58
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT    0
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY_MASK     (0xFF << CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT)
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY(n)       (((n) & CAP_SENS_REG_CONV_EN_INITIAL_DLY_MASK) >> CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT)

// REG_5C
#define CAP_SENS_REG_CONV_WAIT_SHIFT               20
#define CAP_SENS_REG_CONV_WAIT_MASK                (0xFF << CAP_SENS_REG_CONV_WAIT_SHIFT)
#define CAP_SENS_REG_CONV_WAIT(n)                  (((n) & CAP_SENS_REG_CONV_WAIT_MASK) >> CAP_SENS_REG_CONV_WAIT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT        16
#define CAP_SENS_REG_CDC_CORE_RST_CNT_MASK         (0xF << CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_RST_CNT(n)           (((n) & CAP_SENS_REG_CDC_CORE_RST_CNT_MASK) >> CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT      8
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT_MASK       (0xFF << CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT(n)         (((n) & CAP_SENS_REG_CDC_CORE_PWUP_WAIT_MASK) >> CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT)
#define CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT         0
#define CAP_SENS_REG_VREF_PRECHG_CNT_MASK          (0xFF << CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT)
#define CAP_SENS_REG_VREF_PRECHG_CNT(n)            (((n) & CAP_SENS_REG_VREF_PRECHG_CNT_MASK) >> CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT)

// REG_60
#define CAP_SENS_REG_CSENSE_RSEL_SHIFT         26
#define CAP_SENS_REG_CSENSE_RSEL_MASK          (0x3 << CAP_SENS_REG_CSENSE_RSEL_SHIFT)
#define CAP_SENS_REG_CSENSE_RSEL(n)            (((n) & CAP_SENS_REG_CSENSE_RSEL_MASK) >> CAP_SENS_REG_CSENSE_RSEL_SHIFT)
#define CAP_SENS_REG_CREF_SEL_SHIFT            22
#define CAP_SENS_REG_CREF_SEL_MASK             (0xF << CAP_SENS_REG_CREF_SEL_SHIFT)
#define CAP_SENS_REG_CREF_SEL(n)               (((n) & CAP_SENS_REG_CREF_SEL_MASK) >> CAP_SENS_REG_CREF_SEL_SHIFT)
#define CAP_SENS_REG_LDO_VREF_ISEL_SHIFT       19
#define CAP_SENS_REG_LDO_VREF_ISEL_MASK        (0x7 << CAP_SENS_REG_LDO_VREF_ISEL_SHIFT)
#define CAP_SENS_REG_LDO_VREF_ISEL(n)          (((n) & CAP_SENS_REG_LDO_VREF_ISEL_MASK) >> CAP_SENS_REG_LDO_VREF_ISEL_SHIFT)
#define CAP_SENS_REG_LDO_VSEL_SHIFT            16
#define CAP_SENS_REG_LDO_VSEL_MASK             (0x7 << CAP_SENS_REG_LDO_VSEL_SHIFT)
#define CAP_SENS_REG_LDO_VSEL(n)               (((n) & CAP_SENS_REG_LDO_VSEL_MASK) >> CAP_SENS_REG_LDO_VSEL_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_1_SHIFT          12
#define CAP_SENS_REG_LDO_ISEL_1_MASK           (0xF << CAP_SENS_REG_LDO_ISEL_1_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_1(n)             (((n) & CAP_SENS_REG_LDO_ISEL_1_MASK) >> CAP_SENS_REG_LDO_ISEL_1_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_0_SHIFT          8
#define CAP_SENS_REG_LDO_ISEL_0_MASK           (0xF << CAP_SENS_REG_LDO_ISEL_0_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_0(n)             (((n) & CAP_SENS_REG_LDO_ISEL_0_MASK) >> CAP_SENS_REG_LDO_ISEL_0_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_DR               (1 << 7)
#define CAP_SENS_REG_BIAS_ISEL_1_SHIFT         4
#define CAP_SENS_REG_BIAS_ISEL_1_MASK          (0x7 << CAP_SENS_REG_BIAS_ISEL_1_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_1(n)            (((n) & CAP_SENS_REG_BIAS_ISEL_1_MASK) >> CAP_SENS_REG_BIAS_ISEL_1_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_0_SHIFT         1
#define CAP_SENS_REG_BIAS_ISEL_0_MASK          (0x7 << CAP_SENS_REG_BIAS_ISEL_0_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_0(n)            (((n) & CAP_SENS_REG_BIAS_ISEL_0_MASK) >> CAP_SENS_REG_BIAS_ISEL_0_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_DR              (1 << 0)

// REG_64
#define CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT     19
#define CAP_SENS_REG_SAR_VRES_LOGIC_MASK      (0xF << CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT)
#define CAP_SENS_REG_SAR_VRES_LOGIC(n)        (((n) & CAP_SENS_REG_SAR_VRES_LOGIC_MASK) >> CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT)
#define CAP_SENS_REG_SAR_VRES_DLY_SHIFT       15
#define CAP_SENS_REG_SAR_VRES_DLY_MASK        (0xF << CAP_SENS_REG_SAR_VRES_DLY_SHIFT)
#define CAP_SENS_REG_SAR_VRES_DLY(n)          (((n) & CAP_SENS_REG_SAR_VRES_DLY_MASK) >> CAP_SENS_REG_SAR_VRES_DLY_SHIFT)
#define CAP_SENS_REG_SAR_VRES_CMP_SHIFT       11
#define CAP_SENS_REG_SAR_VRES_CMP_MASK        (0xF << CAP_SENS_REG_SAR_VRES_CMP_SHIFT)
#define CAP_SENS_REG_SAR_VRES_CMP(n)          (((n) & CAP_SENS_REG_SAR_VRES_CMP_MASK) >> CAP_SENS_REG_SAR_VRES_CMP_SHIFT)
#define CAP_SENS_REG_SAR_DLY_CTRL             (1 << 10)
#define CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT     8
#define CAP_SENS_REG_RCOSC_FRE_MODE_MASK      (0x3 << CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_MODE(n)        (((n) & CAP_SENS_REG_RCOSC_FRE_MODE_MASK) >> CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT     0
#define CAP_SENS_REG_RCOSC_FRE_TRIM_MASK      (0xFF << CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_TRIM(n)        (((n) & CAP_SENS_REG_RCOSC_FRE_TRIM_MASK) >> CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT)

// REG_68
#define CAP_SENS_REG_FIFO_CLR                 (1 << 4)
#define CAP_SENS_REG_SOFT_MODE                (1 << 3)
#define CAP_SENS_REG_TEST_MODE                (1 << 2)
#define CAP_SENS_REG_DMA_EN                   (1 << 1)
#define CAP_SENS_REG_CAP_SENSOR_EN            (1 << 0)

// REG_6C
#define CAP_SENS_REG_RD_DATA_SHIFT            0
#define CAP_SENS_REG_RD_DATA_MASK             (0x7FFF << CAP_SENS_REG_RD_DATA_SHIFT)
#define CAP_SENS_REG_RD_DATA(n)               (((n) & CAP_SENS_REG_RD_DATA_MASK) >> CAP_SENS_REG_RD_DATA_SHIFT)

// REG_70
#define CAP_SENS_REG_FIFO_EMPTY               (1 << 16) 
#define CAP_SENS_REG_FIFO_DATA_CNT_SHIFT      8
#define CAP_SENS_REG_FIFO_DATA_CNT_MASK       (0x3F << CAP_SENS_REG_FIFO_DATA_CNT_SHIFT)
#define CAP_SENS_REG_FIFO_DATA_CNT(n)         (((n) & CAP_SENS_REG_FIFO_DATA_CNT_MASK) >> CAP_SENS_REG_FIFO_DATA_CNT_SHIFT)
#define CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT    0
#define CAP_SENS_REG_FIFO_ALFULL_LVL_MASK     (0x3F << CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT)
#define CAP_SENS_REG_FIFO_ALFULL_LVL(n)       (((n) & CAP_SENS_REG_FIFO_ALFULL_LVL_MASK) >> CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT)

// REG_74
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT       20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_MASK        (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK(n)          (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT       16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_MASK        (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK(n)          (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT      8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_MASK       (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK(n)         (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT     0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_MASK      (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK(n)        (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT)

// REG_78
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT        20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_MASK         (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR(n)           (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT        16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_MASK         (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR(n)           (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT       8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_MASK        (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR(n)          (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT      0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_MASK       (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR(n)         (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT)

// REG_7C
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT        20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_MASK         (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT(n)           (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT        16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_MASK         (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT(n)           (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT       8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_MASK        (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT(n)          (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT      0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_MASK       (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT(n)         (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT)

// REG_80
#define CAP_SENS_REG_SAR_TEST_LOCK                     (1 << 12)
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT          8
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE_MASK           (0xF << CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE(n)             (((n) & CAP_SENS_REG_SAR_TST_CONV_CYCLE_MASK) << CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT           4
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE_MASK            (0xF << CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE(n)              (((n) & CAP_SENS_REG_SAR_TST_SMP_CYCLE_MASK) << CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_DIG_EN                    (1 << 1)
#define CAP_SENS_REG_SAR_TST_EN                        (1 << 0)

// REG_84
#define CAP_SENS_REG_TPORT_SEL_SHIFT              0
#define CAP_SENS_REG_TPORT_SEL_MASK               (0x7 << CAP_SENS_REG_TPORT_SEL_SHIFT)
#define CAP_SENS_REG_TPORT_SEL(n)                 (((n) & CAP_SENS_REG_TPORT_SEL_MASK) << CAP_SENS_REG_TPORT_SEL_SHIFT)

// REG_88
#define CAP_SENS_REG_DIN_USN_SHIFT                0
#define CAP_SENS_REG_DIN_USN_MASK                 (0xFFF << CAP_SENS_REG_DIN_USN_SHIFT)
#define CAP_SENS_REG_DIN_USN(n)                   (((n) & CAP_SENS_REG_DIN_USN_MASK) << CAP_SENS_REG_DIN_USN_SHIFT)

// REG_8C
#define CAP_SENS_REG_RCOSC_CAL_RESETN            (1 << 4)
#define CAP_SENS_REG_RCOSC_CAL_START             (1 << 3)
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT    0
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL_MASK     (0x7 << CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT)
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL(n)       (((n) & CAP_SENS_REG_RCOSC_CAL_TIME_SEL_MASK) << CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT)

// REG_90
#define CAP_SENS_REG_DIG_RCOSC_CAL_DONE          (1 << 15)
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT     0
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT_MASK      (0x7FFF << CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT)
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT(n)        (((n) & CAP_SENS_REG_DIG_RCOSC_CAL_CNT_MASK) << CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT)

// REG_94
#define CAP_SENS_REG_CAP_CHAN0_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN0_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_CHAN0(n)                (((n) & CAP_SENS_REG_CAP_CHAN0_MASK) << CAP_SENS_REG_CAP_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_CHAN1_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN1_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_CHAN1(n)                (((n) & CAP_SENS_REG_CAP_CHAN1_MASK) << CAP_SENS_REG_CAP_CHAN1_SHIFT)

// REG_98
#define CAP_SENS_REG_CAP_CHAN2_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN2_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_CHAN2(n)                (((n) & CAP_SENS_REG_CAP_CHAN2_MASK) << CAP_SENS_REG_CAP_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_CHAN3_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN3_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_CHAN3(n)                (((n) & CAP_SENS_REG_CAP_CHAN3_MASK) << CAP_SENS_REG_CAP_CHAN3_SHIFT)

// REG_9C
#define CAP_SENS_REG_CAP_CHAN4_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN4_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_CHAN4(n)                (((n) & CAP_SENS_REG_CAP_CHAN4_MASK) << CAP_SENS_REG_CAP_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_CHAN5_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN5_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_CHAN5(n)                (((n) & CAP_SENS_REG_CAP_CHAN5_MASK) << CAP_SENS_REG_CAP_CHAN5_SHIFT)

// REG_A0
#define CAP_SENS_REG_CAP_CHAN6_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN6_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_CHAN6(n)                (((n) & CAP_SENS_REG_CAP_CHAN6_MASK) << CAP_SENS_REG_CAP_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_CHAN7_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN7_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_CHAN7(n)                (((n) & CAP_SENS_REG_CAP_CHAN7_MASK) << CAP_SENS_REG_CAP_CHAN7_SHIFT)

// REG_A4
#define CAP_SENS_REG_RSV0_SHIFT                  0
#define CAP_SENS_REG_RSV0_MASK                   (0xFF << CAP_SENS_REG_RSV0_SHIFT)
#define CAP_SENS_REG_RSV0(n)                     (((n) & CAP_SENS_REG_RSV0_MASK) << CAP_SENS_REG_RSV0_SHIFT)

// REG_A8
#define CAP_SENS_REG_RSV1_SHIFT                  0
#define CAP_SENS_REG_RSV1_MASK                   (0xFF << CAP_SENS_REG_RSV1_SHIFT)
#define CAP_SENS_REG_RSV1(n)                     (((n) & CAP_SENS_REG_RSV1_MASK) << CAP_SENS_REG_RSV1_SHIFT)

#ifdef __cplusplus
}
#endif

#endif // __REG_CAPSENSOR_BEST1501_H__
